/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_laojiang_myaudioprise_util_MixRecord */

#ifndef _Included_com_laojiang_myaudioprise_util_MixRecord
#define _Included_com_laojiang_myaudioprise_util_MixRecord
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_laojiang_myaudioprise_util_MixRecord
 * Method:    decodeMp3ToPCM2
 * Signature: (Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_laojiang_myaudioprise_util_MixRecord_decodeMp3ToPCM2
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     com_laojiang_myaudioprise_util_MixRecord
 * Method:    mix2PCMToPCM
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_laojiang_myaudioprise_util_MixRecord_mix2PCMToPCM
  (JNIEnv *, jobject, jstring, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
